id = "nim"
name = "Nim"
version = "0.0.4"
schema_version = 1
authors = ["Foxoman <sultan@foxoman.net>"]
description = "Nim support"
repository = "https://github.com/foxoman/zed-nim"

[language_servers.nim]
name = "Nim Language Server"
language = "Nim"

[grammars.nim]
repository = "https://github.com/alaviss/tree-sitter-nim"
commit = "897e5d346f0b59ed62b517cfb0f1a845ad8f0ab7"
